# Generated by Django 6.0.1 on 2026-01-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sign', models.CharField(max_length=10, verbose_name='Κωδικός (π.χ. 07)')),
                ('members', models.TextField(blank=True, help_text='Ονόματα και τηλέφωνα')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Τοποθεσία')),
                ('incident_report', models.TextField(blank=True, verbose_name='Αναφορά Περιστατικού')),
                ('status', models.CharField(choices=[('GREEN', 'Πράσινο - Ελεύθερη'), ('YELLOW', 'Κίτρινο - Περιπολία'), ('RED', 'Κόκκινο - Περιστατικό'), ('PURPLE', 'Μωβ - Σταθερό Σημείο')], default='GREEN', max_length=10)),
            ],
        ),
    ]
