# Generated by Django 6.0.1 on 2026-01-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.AlterField(
            model_name='team',
            name='call_sign',
            field=models.CharField(max_length=10, verbose_name='Κωδικός'),
        ),
        migrations.AlterField(
            model_name='team',
            name='incident_report',
            field=models.TextField(blank=True, verbose_name='Περιγραφή Περιστατικού'),
        ),
    ]
