# Generated by Django 6.0.1 on 2026-01-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_remove_team_members_alter_team_call_sign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='call_sign',
            field=models.CharField(max_length=10, unique=True, verbose_name='Κωδικός'),
        ),
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('OFF', 'Standby / Εκτός'), ('GREEN', 'Πράσινο - Ελεύθερη'), ('YELLOW', 'Κίτρινο - Περιπολία'), ('RED', 'Κόκκινο - Περιστατικό'), ('PURPLE', 'Μωβ - Σταθερό Σημείο')], default='OFF', max_length=10),
        ),
    ]
