# Generated by Django 6.0.1 on 2026-01-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_team_updated_at_alter_team_call_sign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='leader_full_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ονοματεπώνυμο Υπευθύνου'),
        ),
        migrations.AddField(
            model_name='team',
            name='leader_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Τηλέφωνο Υπευθύνου'),
        ),
        migrations.AddField(
            model_name='team',
            name='members_list',
            field=models.TextField(blank=True, verbose_name='Μέλη Ομάδας'),
        ),
        migrations.AlterField(
            model_name='team',
            name='incident_report',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
